<?php
/**
 * CharacteristicsApi
 * PHP version 8.1
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KB-Freezebee API
 *
 * This is the API for the freezebee managing microservice for the KillerBee web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Infrastructure\Freezebee;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use App\Infrastructure\FreezebeeException;
use App\Infrastructure\Freezebee\HeaderSelector;
use App\Infrastructure\Freezebee\ObjectSerializer;
use App\Infrastructure\Freezebee\ApiException;

/**
 * CharacteristicsApi Class Doc Comment
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CharacteristicsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createCharacteristic' => [
            'application/json',
        ],
        'getCharacteristic' => [
            'application/json',
        ],
        'modifyCharacteristic' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createCharacteristic
     *
     * Creates a new characteristic.
     *
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Create an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return App\Model\FreezebeeDTO\CharacteristicOutput
     */
    public function createCharacteristic($characteristic_input, string $contentType = self::contentTypes['createCharacteristic'][0])
    {
        list($response) = $this->createCharacteristicWithHttpInfo($characteristic_input, $contentType);
        return $response;
    }

    /**
     * Operation createCharacteristicWithHttpInfo
     *
     * Creates a new characteristic.
     *
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Create an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return App\Model\FreezebeeDTO\CharacteristicOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function createCharacteristicWithHttpInfo($characteristic_input, string $contentType = self::contentTypes['createCharacteristic'][0])
    {
        $request = $this->createCharacteristicRequest($characteristic_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'App\Model\FreezebeeDTO\CharacteristicOutput',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'App\Model\FreezebeeDTO\CharacteristicOutput',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Model\FreezebeeDTO\CharacteristicOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createCharacteristicAsync
     *
     * Creates a new characteristic.
     *
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Create an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCharacteristicAsync($characteristic_input, string $contentType = self::contentTypes['createCharacteristic'][0])
    {
        return $this->createCharacteristicAsyncWithHttpInfo($characteristic_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createCharacteristicAsyncWithHttpInfo
     *
     * Creates a new characteristic.
     *
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Create an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCharacteristicAsyncWithHttpInfo($characteristic_input, string $contentType = self::contentTypes['createCharacteristic'][0])
    {
        $returnType = 'App\Model\FreezebeeDTO\CharacteristicOutput';
        $request = $this->createCharacteristicRequest($characteristic_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createCharacteristic'
     *
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Create an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createCharacteristicRequest($characteristic_input, string $contentType = self::contentTypes['createCharacteristic'][0])
    {

        // verify the required parameter 'characteristic_input' is set
        if ($characteristic_input === null || (is_array($characteristic_input) && count($characteristic_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $characteristic_input when calling createCharacteristic'
            );
        }


        $resourcePath = '/characteristic/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($characteristic_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($characteristic_input));
            } else {
                $httpBody = $characteristic_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCharacteristic
     *
     * Fetches all characteristic.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return App\Model\FreezebeeDTO\CharacteristicOutput
     */
    public function getCharacteristic(string $contentType = self::contentTypes['getCharacteristic'][0])
    {
        list($response) = $this->getCharacteristicWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getCharacteristicWithHttpInfo
     *
     * Fetches all characteristics.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of App\Model\FreezebeeDTO\CharacteristicOutput[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getCharacteristicWithHttpInfo(string $contentType = self::contentTypes['getCharacteristic'][0])
    {
        $request = $this->getCharacteristicRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'App\Model\FreezebeeDTO\CharacteristicOutput[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'App\Model\FreezebeeDTO\CharacteristicOutput[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Model\FreezebeeDTO\CharacteristicOutput[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCharacteristicAsync
     *
     * Fetches all characteristic.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCharacteristicAsync(string $contentType = self::contentTypes['getCharacteristic'][0])
    {
        return $this->getCharacteristicAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCharacteristicAsyncWithHttpInfo
     *
     * Fetches all characteristic.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCharacteristicAsyncWithHttpInfo(string $contentType = self::contentTypes['getCharacteristic'][0])
    {
        $returnType = 'App\Model\FreezebeeDTO\CharacteristicOutput[]';
        $request = $this->getCharacteristicRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCharacteristic'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCharacteristicRequest(string $contentType = self::contentTypes['getCharacteristic'][0])
    {


        $resourcePath = '/characteristic/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation modifyCharacteristic
     *
     * Updates an characteristic.
     *
     * @param  string $characteristic_id Numeric ID of the characteristic. (required)
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Modify an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return App\Model\FreezebeeDTO\CharacteristicOutput[]
     */
    public function modifyCharacteristic($characteristic_id, $characteristic_input, string $contentType = self::contentTypes['modifyCharacteristic'][0])
    {
        list($response) = $this->modifyCharacteristicWithHttpInfo($characteristic_id, $characteristic_input, $contentType);
        return $response;
    }

    /**
     * Operation modifyCharacteristicWithHttpInfo
     *
     * Updates an characteristic.
     *
     * @param  string $characteristic_id Numeric ID of the characteristic. (required)
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Modify an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyCharacteristic'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return App\Model\FreezebeeDTO\CharacteristicOutput, HTTP status code, HTTP response headers (array of strings)
     */
    public function modifyCharacteristicWithHttpInfo($characteristic_id, $characteristic_input, string $contentType = self::contentTypes['modifyCharacteristic'][0])
    {
        $request = $this->modifyCharacteristicRequest($characteristic_id, $characteristic_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'App\Model\FreezebeeDTO\CharacteristicOutput',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'App\Model\FreezebeeDTO\CharacteristicOutput',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'App\Model\FreezebeeDTO\CharacteristicOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation modifyCharacteristicAsync
     *
     * Updates an characteristic.
     *
     * @param  string $characteristic_id Numeric ID of the characteristic. (required)
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Modify an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyCharacteristicAsync($characteristic_id, $characteristic_input, string $contentType = self::contentTypes['modifyCharacteristic'][0])
    {
        return $this->modifyCharacteristicAsyncWithHttpInfo($characteristic_id, $characteristic_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation modifyCharacteristicAsyncWithHttpInfo
     *
     * Updates an characteristic.
     *
     * @param  string $characteristic_id Numeric ID of the characteristic. (required)
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Modify an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyCharacteristicAsyncWithHttpInfo($characteristic_id, $characteristic_input, string $contentType = self::contentTypes['modifyCharacteristic'][0])
    {
        $returnType = 'App\Model\FreezebeeDTO\CharacteristicOutput';
        $request = $this->modifyCharacteristicRequest($characteristic_id, $characteristic_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'modifyCharacteristic'
     *
     * @param  string $characteristic_id Numeric ID of the characteristic. (required)
     * @param  App\Model\FreezebeeDTO\CharacteristicInput $characteristic_input Modify an characteristic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyCharacteristic'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function modifyCharacteristicRequest($characteristic_id, $characteristic_input, string $contentType = self::contentTypes['modifyCharacteristic'][0])
    {

        // verify the required parameter 'characteristic_id' is set
        if ($characteristic_id === null || (is_array($characteristic_id) && count($characteristic_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $characteristic_id when calling modifyCharacteristic'
            );
        }

        // verify the required parameter 'characteristic_input' is set
        if ($characteristic_input === null || (is_array($characteristic_input) && count($characteristic_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $characteristic_input when calling modifyCharacteristic'
            );
        }


        $resourcePath = '/characteristic/{characteristicId}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($characteristic_id !== null) {
            $resourcePath = str_replace(
                '{' . 'characteristicId' . '}',
                ObjectSerializer::toPathValue($characteristic_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($characteristic_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($characteristic_input));
            } else {
                $httpBody = $characteristic_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
