<?php
/**
 * IngredientsApi
 * PHP version 8.1
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KB-Freezebee API
 *
 * This is the API for the freezebee managing microservice for the KillerBee web app
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Infrastructure\Freezebee;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use App\Infrastructure\Freezebee\FreezebeeException;
use App\Infrastructure\Freezebee\C;
use App\Infrastructure\Freezebee\FormDataProcessor;
use App\Infrastructure\Freezebee\HeaderSelector;
use App\Infrastructure\Freezebee\ObjectSerializer;
use App\Infrastructure\Freezebee\ApiException;

/**
 * IngredientsApi Class Doc Comment
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IngredientsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createIngredients' => [
            'application/json',
        ],
        'getIngredients' => [
            'application/json',
        ],
        'modifyIngredients' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createIngredients
     *
     * Creates a new ingredient.
     *
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Create an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\IngredientOutput[]
     */
    public function createIngredients($ingredient_input, string $contentType = self::contentTypes['createIngredients'][0])
    {
        list($response) = $this->createIngredientsWithHttpInfo($ingredient_input, $contentType);
        return $response;
    }

    /**
     * Operation createIngredientsWithHttpInfo
     *
     * Creates a new ingredient.
     *
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Create an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\IngredientOutput[], HTTP status code, HTTP response headers (array of strings)
     */
    public function createIngredientsWithHttpInfo($ingredient_input, string $contentType = self::contentTypes['createIngredients'][0])
    {
        $request = $this->createIngredientsRequest($ingredient_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\IngredientOutput[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createIngredientsAsync
     *
     * Creates a new ingredient.
     *
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Create an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createIngredientsAsync($ingredient_input, string $contentType = self::contentTypes['createIngredients'][0])
    {
        return $this->createIngredientsAsyncWithHttpInfo($ingredient_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createIngredientsAsyncWithHttpInfo
     *
     * Creates a new ingredient.
     *
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Create an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createIngredientsAsyncWithHttpInfo($ingredient_input, string $contentType = self::contentTypes['createIngredients'][0])
    {
        $returnType = '\OpenAPI\Client\Model\IngredientOutput[]';
        $request = $this->createIngredientsRequest($ingredient_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createIngredients'
     *
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Create an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createIngredientsRequest($ingredient_input, string $contentType = self::contentTypes['createIngredients'][0])
    {

        // verify the required parameter 'ingredient_input' is set
        if ($ingredient_input === null || (is_array($ingredient_input) && count($ingredient_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ingredient_input when calling createIngredients'
            );
        }


        $resourcePath = '/ingredient/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ingredient_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ingredient_input));
            } else {
                $httpBody = $ingredient_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getIngredients
     *
     * Fetches all ingredients.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\IngredientOutput[]
     */
    public function getIngredients(string $contentType = self::contentTypes['getIngredients'][0])
    {
        list($response) = $this->getIngredientsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getIngredientsWithHttpInfo
     *
     * Fetches all ingredients.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\IngredientOutput[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getIngredientsWithHttpInfo(string $contentType = self::contentTypes['getIngredients'][0])
    {
        $request = $this->getIngredientsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\IngredientOutput[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getIngredientsAsync
     *
     * Fetches all ingredients.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIngredientsAsync(string $contentType = self::contentTypes['getIngredients'][0])
    {
        return $this->getIngredientsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getIngredientsAsyncWithHttpInfo
     *
     * Fetches all ingredients.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIngredientsAsyncWithHttpInfo(string $contentType = self::contentTypes['getIngredients'][0])
    {
        $returnType = '\OpenAPI\Client\Model\IngredientOutput[]';
        $request = $this->getIngredientsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getIngredients'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getIngredientsRequest(string $contentType = self::contentTypes['getIngredients'][0])
    {


        $resourcePath = '/ingredient/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation modifyIngredients
     *
     * Updates an ingredient.
     *
     * @param  string $ingredient_id Numeric ID of the ingredient. (required)
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Modify an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\IngredientOutput[]
     */
    public function modifyIngredients($ingredient_id, $ingredient_input, string $contentType = self::contentTypes['modifyIngredients'][0])
    {
        list($response) = $this->modifyIngredientsWithHttpInfo($ingredient_id, $ingredient_input, $contentType);
        return $response;
    }

    /**
     * Operation modifyIngredientsWithHttpInfo
     *
     * Updates an ingredient.
     *
     * @param  string $ingredient_id Numeric ID of the ingredient. (required)
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Modify an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyIngredients'] to see the possible values for this operation
     *
     * @throws \App\Infrastructure\FreezebeeException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\IngredientOutput[], HTTP status code, HTTP response headers (array of strings)
     */
    public function modifyIngredientsWithHttpInfo($ingredient_id, $ingredient_input, string $contentType = self::contentTypes['modifyIngredients'][0])
    {
        $request = $this->modifyIngredientsRequest($ingredient_id, $ingredient_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\IngredientOutput[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\IngredientOutput[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation modifyIngredientsAsync
     *
     * Updates an ingredient.
     *
     * @param  string $ingredient_id Numeric ID of the ingredient. (required)
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Modify an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyIngredientsAsync($ingredient_id, $ingredient_input, string $contentType = self::contentTypes['modifyIngredients'][0])
    {
        return $this->modifyIngredientsAsyncWithHttpInfo($ingredient_id, $ingredient_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation modifyIngredientsAsyncWithHttpInfo
     *
     * Updates an ingredient.
     *
     * @param  string $ingredient_id Numeric ID of the ingredient. (required)
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Modify an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyIngredientsAsyncWithHttpInfo($ingredient_id, $ingredient_input, string $contentType = self::contentTypes['modifyIngredients'][0])
    {
        $returnType = '\OpenAPI\Client\Model\IngredientOutput[]';
        $request = $this->modifyIngredientsRequest($ingredient_id, $ingredient_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'modifyIngredients'
     *
     * @param  string $ingredient_id Numeric ID of the ingredient. (required)
     * @param  \OpenAPI\Client\Model\IngredientInput $ingredient_input Modify an ingredient (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['modifyIngredients'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function modifyIngredientsRequest($ingredient_id, $ingredient_input, string $contentType = self::contentTypes['modifyIngredients'][0])
    {

        // verify the required parameter 'ingredient_id' is set
        if ($ingredient_id === null || (is_array($ingredient_id) && count($ingredient_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ingredient_id when calling modifyIngredients'
            );
        }

        // verify the required parameter 'ingredient_input' is set
        if ($ingredient_input === null || (is_array($ingredient_input) && count($ingredient_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ingredient_input when calling modifyIngredients'
            );
        }


        $resourcePath = '/ingredient/{ingredientId}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($ingredient_id !== null) {
            $resourcePath = str_replace(
                '{' . 'ingredientId' . '}',
                ObjectSerializer::toPathValue($ingredient_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ingredient_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ingredient_input));
            } else {
                $httpBody = $ingredient_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
